### ISSUE TITLE
Instalation on macOS Ventura 13.1 M1 fails

### ISSUE THREAD

**Issue by dchimeno** [auxten/chdb#1]
> pip install chdb

ERROR: Could not find a version that satisfies the requirement chdb (from versions: none)
ERROR: No matching distribution found for chdb

> uname -a
Darwin xxxx 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64

> python -V
Python 3.10.9

**Comment by auxten** [comment]
Currently, I haven't compiled chdb into the ARM64(M1) arch.
Maybe, you can try the following command:
```bash
arch -x86_64 pip install chdb
arch -x86_64 python3 -c \
    "import chdb; res = chdb.query('select version()', 'CSV'); print(str(res.get_memview().tobytes()))" 
```

**Comment by auxten** [comment]
macOS arm64 for python 3.10 is published @dchimeno
