### ISSUE TITLE
Pandas dataframe output introduced pyarrow and pandas dependency

### ISSUE THREAD

**Issue by auxten** [auxten/chdb#11]
Pandas dataframe output introduced pyarrow and pandas dependency #6 will be released at `v0.5.0`
I'm thinking about whether it's worth it, after all, the size of pyarrow and pandas is not small. Initiate a vote here, think:
1. It is worthwhile to add pyarrow and pandas dependencies to support dataframe, please click 👍
2. If you think it is not worth it, please click 👎

**Comment by auxten** [comment]
There is a possible implementation for discussion: don't add pyarrow or pandas to chdb's install_requires. Only when related functions are used, for example, when using DataFrame format as output, test whether there are pyarrow and pandas versions that meet the requirements. If not, an error will be reported and the user will be prompted to install them.
I don't know if there is a precedent for this practice in the python library. We can discuss it here.
@nmreadelf

**Comment by lmangani** [comment]
> error will be reported and the user will be prompted to install them.

This sounds like the best route. Clear error and Manual installation for those who want/need them.
