### ISSUE TITLE
AVX2 Support

### ISSUE THREAD

**Issue by lmangani** [auxten/chdb#7]
Great mod and very interesting binding approach! We're also [playing](https://blog.qryn.dev/wrapping-a-serverless-clickhouse-pt1) with clickhouse-local custom builds towards a slimmer execution engine. 

Question: Is there a specific reason for AVX2 to be [enabled](https://github.com/auxten/chdb/blob/ab2afa8b94980bfd4551a66fcb6d82922f3fbfcc/chdb/build.sh#L46) for Linux systems? This greatly reduces the scope of usage _(ie: lambdas, virtualized cpus, etc, fail with `Instruction check fail. The CPU does not support AVX2 instruction set.`)_ 

Having this disabled (or possibly multiple versions) could broaden compatibility scope enormously. Also the library doesn't seem to be stripped and the distributed .so has 100M+ of trimmable fat.

Thanks!

**Comment by auxten** [comment]
Thank you for your suggestion. Before, I just thought that most Linux servers should have AVX2 support for performance considerations. Didn't realize usage scenarios like lambdas, virtualized cpus. I'm going to fix this in v0.5.0.

**Comment by lmangani** [comment]
Thanks! If you would like to support AWS Lambdas and other virtualized system the following patch is also required:

```
sed -i '/Cannot set thread name/c\' /ClickHouse/src/Common/setThreadName.cpp
```

Would you accept PRs to the builder?

**Comment by auxten** [comment]
PR is welcome.

**Comment by auxten** [comment]
The strip issue is mainly because currently chdb is really new. I need debug info if any crash happens.
The shared lib is built in release mode but with `-g` flag which means not so much(increased the size by approximately 20%) debug info included.

**Comment by lmangani** [comment]
That makes sense, although the resulting file is really huge. `chdb` x86_64 library as installed by pip3
```
-rwxr-xr-x   1 root staff 527420816 Apr 15 15:37 _chdb.cpython-37m-x86_64-linux-gnu.so*
```
after `strip`
```
-rwxr-xr-x   1 root staff 411978416 Apr 15 15:55 _chdb.cpython-37m-x86_64-linux-gnu.so*
```

**Comment by lmangani** [comment]
PR open, moving discussion in thread: https://github.com/auxten/chdb/pull/9
